import { useEffect, useState } from 'react';
import type { SeedSource } from '@shared/types';

/**
 * The seed bank manifest is a static public asset (generated by
 * `npm run seed`, read server-side by GameStore) that's ALSO reachable
 * directly by the client at /seed/manifest.json — no new protocol message
 * needed to let the Lobby preview/shuffle candidate wire photos client-side.
 * Fetched once per page load and cached at module scope.
 */
let cache: SeedSource[] | null = null;
let inflight: Promise<SeedSource[]> | null = null;

async function loadManifest(): Promise<SeedSource[]> {
  if (cache) return cache;
  if (!inflight) {
    inflight = fetch('/seed/manifest.json')
      .then((res) => (res.ok ? res.json() : Promise.reject(new Error(`${res.status}`))))
      .then((data: SeedSource[]) => { cache = data; return data; })
      .catch(() => { inflight = null; return []; });
  }
  return inflight;
}

export function useSeedBank(): SeedSource[] {
  const [sources, setSources] = useState<SeedSource[]>(cache ?? []);
  useEffect(() => {
    if (cache) { setSources(cache); return; }
    let cancelled = false;
    loadManifest().then((data) => { if (!cancelled) setSources(data); });
    return () => { cancelled = true; };
  }, []);
  return sources;
}

/** A random id, optionally excluding one (e.g. don't re-show the same card
 * on shuffle). Falls back to including it if it's the only option. */
export function randomSeedId(sources: SeedSource[], exclude?: string | null): string | null {
  if (sources.length === 0) return null;
  const pool = sources.length > 1 ? sources.filter((s) => s.id !== exclude) : sources;
  return pool[Math.floor(Math.random() * pool.length)].id;
}
