services:
  - type: web
    name: editor-in-grief
    runtime: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    healthCheckPath: /health
    autoDeployTrigger: commit
